USE School;
GO

DROP TABLE IF EXISTS StudentAssignment;
DROP TABLE IF EXISTS Grade;
DROP TABLE IF EXISTS Assignment;
DROP TABLE IF EXISTS TCS;
DROP TABLE IF EXISTS ClassSemester;
DROP TABLE IF EXISTS Student;

DROP TABLE IF EXISTS Class;
DROP TABLE IF EXISTS Teacher;
DROP TABLE IF EXISTS Subject;
DROP TABLE IF EXISTS Semester;
